[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]

[tool.setuptools_scm]
local_scheme = "no-local-version"

[tool.black]
skip-string-normalization = true
line-length = 100